name: Build and Push Dist

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and Build
        working-directory: frontend # 
        run: |
          npm ci
          npm run build

      - name: Copy dist to proxy/static/dist
        run: |
          rm -rf proxy/static/dist
          cp -r frontend/dist proxy/static/dist

      - name: Commit and push dist
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add proxy/static/dist
          git commit -m "🤖 Auto-build dist from GitHub Actions" || echo "No changes to commit"
          git push
